# Linear Algebra

- we learn about
- Creating matrices using attributes of matrices 
- How to find transforms and inverses and identity
- techniques that use matrices to solve systems of linear equations - techniques to generate eigenvalues and eigenvectors.

In [2]:
import numpy as np

### Matrix

- Returns a matrix from an array-like object, or from a string of data. 
- https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.matrix.html

In [4]:
my_first_matrix=np.matrix([[3,1,4],[1,5,9],[2,6,5]])
my_first_matrix #here see the output type is MATRIX not ndarray

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [5]:
#A matrix is a specialized 2D array that retains its 2D nature through operations. 
#It has certain special operators such as asterisk from matrix multiplication, 
# and a double asterisk for matrix power or matrix exponentiation operations.

#### Transpose M

In [6]:
my_first_matrix.T # RETURNS transpose of matrix

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

####  Inverse M

In [7]:
my_first_matrix.I #Inverse of matrix

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

#### Identity M

In [10]:
#Identity Matrix - DIAGNOALLY ELEMENTS ARE SAME
# m x m.I
my_first_matrix * my_first_matrix.I


matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
        [ 5.55111512e-17, -1.38777878e-16,  1.00000000e+00]])

In [11]:
#We can use NumPy Eye function to create identity function directly
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Solving simultaneous linear equation

$$ ax=b $$

- a is Coefficient matrix.
- b is Ordinate or “dependent variable” values.
- x is Solution to the system a x = b. Returned shape is identical to b.

In [13]:
# An important use of linear algebra is solving
#systems of simultaneous linear equations. 
#Our three by three matrix can represent a system of 
#three equations with three unknowns.

In [16]:
right_hand_side = np.matrix([[11],
                           [22],
                           [33]])

In [17]:
#Above right hand side matrix 
#represents the values on the 
#right hand side of each of three equations

In [18]:
# Let's create a variable called my first inverse, 
#and assign it the value of my first matrix inverse. 
my_first_inverse =my_first_matrix.I

In [19]:
#Let's find the solution to this system of linear equations.
#We can do this by creating a variable called solution,
#use my first inverse,
#and matrix multiplication operator, and right hand side.
SOLUTION = my_first_inverse * right_hand_side

In [20]:
SOLUTION

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [21]:
#lets test the solution
my_first_matrix *SOLUTION - right_hand_side

matrix([[ 0.00000000e+00],
        [-3.55271368e-15],
        [ 7.10542736e-15]])

In [22]:
# if we have a large matrices it becomes lengthy
#for this we have special module 

### numpy.linalg

In [24]:
# we can solve the above with simple solve function
#solve - Solves a linear matrix equation
# with a simple step, it solves the linear equation
from numpy.linalg import solve
solve(my_first_matrix,right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [27]:
my_first_matrix*SOLUTION #henerates right hand side matric
#ieeee ax=b ie linear equation

matrix([[11.],
        [22.],
        [33.]])

### eigen values and eigen vectors

- EIG function

In [28]:
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))