### Slicing Array

In [4]:
#Elements in numpy array are index based
import numpy as np
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [5]:
#we can select array by typing the index of element
my_vector[0]

-17

In [8]:
#reassign or modify value
my_vector[0]=-102
my_vector[0]

-102

In [12]:
#indices can be negative numbers
#to acces the values in reverse side but
#the reverse side starts from index -1
my_vector[-2]

37

In [13]:
#getting size
my_vector.size

7

In [15]:
#you can use arithemetic to access index
my_vector[12%5] #gives my_vector[2]

0

### Two dimensional Arrays

In [18]:
my_2d_array=np.arange(35) #creates 1 D array with 35 elements starting from 0
my_2d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [20]:
my_2d_array.shape=(7,5)  #creating 2D array using the shape and tuple
my_2d_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [21]:
#slicing 2 d array
my_2d_array[2] #gives 3 rd row..row index starts from 0

array([10, 11, 12, 13, 14])

In [22]:
#same way as 1 D , we can use negative number
my_2d_array[-1]

array([30, 31, 32, 33, 34])

In [28]:
#To access sepecific element in 2D
#my_array(row,column)
my_2d_array[0,2] #currently we have put everything in single []


2

In [27]:
#we can use [][]
my_2d_array[0][3]

3

### Three dimensional array

In [37]:
my_3d_array=np.arange(70)
my_3d_array.shape=(2,7,5) # 7 x5 - 2 times
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [39]:
 #now if you want to access first 2d array in 3d array
my_3d_array[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [40]:
#so now to access second row in first 2d array of 3d array
my_3d_array[0,1]

array([5, 6, 7, 8, 9])

In [41]:
#so now to access first element in second row in first 2d array of 3d array
my_3d_array[0,1,0]

5

In [42]:
#To modify an element in a 2D or 3D
#access and use assignment operator
my_3d_array[0,1,0]=30
my_3d_array[0][1][0]

30