### Boolean Mask Arrays

In [1]:
import numpy as np

In [2]:
my_vector = np.array([-17,-4,0,2,21,37,105]) #populating nump array with python list
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [3]:
zero_mode_7_mask=0==(my_vector % 7) #creates boolean array based on 0==(my_vector % 7)
zero_mode_7_mask

array([False, False,  True, False,  True, False,  True])

In [4]:
#below sub_array is the boolean masked array
#my_vector[zero_mode_7_mask] - mean my_vector is indexed with zero_mode_7_mask array
sub_array=my_vector[zero_mode_7_mask] # will return only elements that are in true position
sub_array # will give only elements of my_array is true based on zero_mode_7_mask

array([  0,  21, 105])

In [5]:
sub_array[sub_array>0] # next level of manipulating ..will return only elements >0

array([ 21, 105])

In [6]:
sub_array #original not modified

array([  0,  21, 105])

In [7]:
my_new_array=np.array([1,2])
my_bool_array=[False,True]
my_array=my_new_array[my_bool_array]
my_array

array([2])

### Numpy logical operators

In [28]:
#below gives alternative method doing the same as above
mod_test = 0 == (my_vector % 7)
mod_test

array([False, False,  True, False,  True, False,  True])

In [29]:
positive_test=my_vector>0 #will return true or false for every element based on >0
positive_test

array([False, False, False,  True,  True,  True,  True])

In [30]:
combined_mask=np.logical_and(mod_test,positive_test) #logical AND between two boolean arrays
combined_mask

array([False, False, False, False,  True, False,  True])

In [34]:
#now we can use combined_mask to index my_vector
my_vector[combined_mask]


array([ 21, 105])

In [ ]:
#Above is the same result that we got before
#difference is first we used python logical operators and in the second we used
#NumPy Logical operators
#Whats the advantage? when dealing with large no of arrays..numpy array is better