###  Broadcasting

In [1]:
import numpy as np

In [2]:
#creating 3 d array
my_3d_array = np.arange(70)
my_3d_array.shape=(2,7,5) #setting shape with atuple
my_3d_array #has 2 - 2D array, observer three [[[]]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [3]:
#Broadcasting describes how numpy performs operations between 
#arrays with different sizes

#Numpy requires that the arrays should be COMPATIBLE before braodcasting can take place
#Compatible means - sizes are same or at the least one of the array size is zero

#A small array BROADCAST to larger array

In [4]:
#before we proceed we need to know attributes of array
#shapes, number dimensions, sizes and data types  
#lets see how to access these attributes

In [5]:
#Shape
#accessing it 
my_3d_array.shape

(2, 7, 5)

In [6]:
#number of dimensions - ndim
my_3d_array.ndim

3

In [7]:
#size - no of elements  
my_3d_array.size
# we can also find out by we passed arange as 70
#and also shape is (2,7,5) - means 2 x 7 x 5

70

In [8]:
#Accessing each data type of element 
my_3d_array.dtype

dtype('int64')

In [9]:
#Now lets start with broadcasting
#using Scalars
5 * my_3d_array -2 #multiplies every element with 5 and then subtracts 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [10]:
#we can create and shape an arary directly using reshape() method
left_mat = np.arange(6).reshape((2,3))  #
right_mat=np.arange(15).reshape(3,5) #Marices special type in NumPy..these are just ordinary ndarray

In [11]:
#numpy has two methods to perform these operations
#numpy.inner & numpy.dot
#inner works only on 1D
#dot works on multi dimensional
#np.inner(left_mat,right_mat) # u get error since both arrays multi
np.dot(left_mat,right_mat) # dot - for 2D equivalent to matrix multiplication
#for 1D - 

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [39]:
left_mat1 = np.arange(6)  #
left_mat1

array([0, 1, 2, 3, 4, 5])

In [40]:
right_mat1=np.arange(6)
right_mat1

array([0, 1, 2, 3, 4, 5])

In [42]:
np.dot(left_mat1,right_mat1) # 

55

In [46]:
np.multiply(left_mat1,right_mat1)

array([ 0,  1,  4,  9, 16, 25])

In [47]:
np.multiply(left_mat1,right_mat1).sum()

55

### Operations along axes

In [13]:
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [14]:
my_3d_array.shape

(2, 7, 5)

In [15]:
my_3d_array.sum() # returns sum of all the elements in an arary

2415

In [16]:
#0 to 69..naturalnumbers...sum of natural numbers ...formula is n(n+1)/2
(69*70)/2

2415.0

In [17]:
#above is same as sum returned result
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [18]:
my_3d_array.shape

(2, 7, 5)

In [19]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [20]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [21]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting rules

In [22]:
#NumPy's documentation tells us that the smaller array is broadcast across the larger array so that they have compatible shapes
my_2d_array=np.ones(35,dtype='int_').reshape((7,5))*3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
my_random_2d_array=np.random.random((7,5))
my_random_2d_array

array([[0.33877477, 0.58007754, 0.71422711, 0.43375285, 0.19447579],
       [0.04359861, 0.35439972, 0.94210842, 0.17747596, 0.03354292],
       [0.55753324, 0.76511402, 0.95677443, 0.05299355, 0.93576974],
       [0.79570498, 0.11289885, 0.70255291, 0.77710169, 0.26332905],
       [0.65791421, 0.66593451, 0.2470162 , 0.08295568, 0.17261734],
       [0.67609338, 0.05288788, 0.73288454, 0.98436531, 0.81595214],
       [0.34937886, 0.72333638, 0.15588529, 0.5572943 , 0.4857901 ]])

In [24]:
np.set_printoptions(precision=4)
my_random_2d_array.shape


(7, 5)

In [25]:
my_3d_array*my_random_2d_array

array([[[ 0.    ,  0.5801,  1.4285,  1.3013,  0.7779],
        [ 0.218 ,  2.1264,  6.5948,  1.4198,  0.3019],
        [ 5.5753,  8.4163, 11.4813,  0.6889, 13.1008],
        [11.9356,  1.8064, 11.9434, 13.9878,  5.0033],
        [13.1583, 13.9846,  5.4344,  1.908 ,  4.1428],
        [16.9023,  1.3751, 19.7879, 27.5622, 23.6626],
        [10.4814, 22.4234,  4.9883, 18.3907, 16.5169]],

       [[11.8571, 20.8828, 26.4264, 16.4826,  7.5846],
        [ 1.7439, 14.5304, 39.5686,  7.6315,  1.4759],
        [25.089 , 35.1952, 44.9684,  2.5437, 45.8527],
        [39.7852,  5.7578, 36.5328, 41.1864, 14.2198],
        [36.1853, 37.2923, 14.0799,  4.8114, 10.1844],
        [40.5656,  3.2262, 45.4388, 62.015 , 52.2209],
        [22.7096, 47.7402, 10.4443, 37.896 , 33.5195]]])

In [26]:
my_vector=np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [27]:
my_3d_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [28]:
my_3d_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])