# Views and Copies

In [1]:
import numpy as np

In [2]:
mi_casa=np.array([-45,-31,-12,0,2,25,51,99])

In [3]:
su_casa=mi_casa

### Are both same?

In [4]:
su_casa is mi_casa

True

In [5]:
id(su_casa)

4463364656

In [6]:
id(mi_casa)

4463364656

In [7]:
#value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
#change a value
su_casa[4]=1010
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [12]:
#there is impact
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [13]:
#create a new variable
tree_house=np.array([-45,-31,-12,0,1010,25,51,99])

In [16]:
#tree house has same elements as that of mi_casa
#lets test both are same?
tree_house==mi_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

### Is it same?

In [19]:
tree_house is mi_casa

False

In [20]:
id(tree_house)

4463451712

In [21]:
id(mi_casa)

4463364656

In [22]:
#So even though both have same values but
#they refer to different memory locations


## Views: A shallow copy

In [39]:
#a View created by using view() method on an array
farm_house=tree_house.view()
#farm_house.shape=(2,4)

In [40]:
tree_house #It is 1 DIMENSIONAL

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

In [42]:
farm_house #IT IS 2 Dimensional

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

### Are these connected?

In [43]:
tree_house[1]=200

In [55]:
farm_house

array([[ -45,  200,  -12,    0],
       [1010,   25,   51,   99]])

In [45]:
#changes got reflected
#so elements of view and array are located at the same memory location

In [48]:
id(tree_house)

4463451712

In [49]:
id(farm_house)

4464095760

In [ ]:
tree_house is farm_house 
#gives you false bcoz one is 1D and other is 2d or 1d it wont be the same
#EVEN THOUGH BOTH ARE in same memory location

In [50]:
#we can also make view into multi dimensional
farm_house.shape=(2,4)
farm_house

array([[ -45,  200,  -12,    0],
       [1010,   25,   51,   99]])

### Deep Copy

In [32]:
#Deep copy created by using copy function
dog_house=np.copy(tree_house)

In [54]:
#lets modify and see
dog_house[0]=-121
#dog_house.shape=(2,4)
#dog_house
#we can make it into multi D

In [34]:
tree_house

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

In [37]:
#so both are in different memory locations when we use deep copy

In [ ]:
#Thats the difference between Views and Copy
#views share same memory location ie provides multiple references to same memory location
#copy as name says copied to a new memory location ie duplicates data into different memory locations