# Joining And Splitting Array

- concatenate
- stack
- split

In [1]:
import numpy as np

### 1.Concatenate
- concatenate((a1, a2, ...), axis=0, out=None)
- #Join a sequence of arrays along an existing axis.

In [2]:
#lets create two arrays
a= np.array([[1,2],[3,4]])
b=np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b.shape

(1, 2)

In [19]:
together = np.concatenate((a,b), axis=0)
#concatenate((a1, a2, ...), axis=0, out=None)
#Join a sequence of arrays along an existing axis.
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
together.shape

(3, 2)

In [14]:
#with append, the original list is simply modified. 
#On the other hand, with concatenation, an entirely new list is created.

In [15]:
together[1,1]=999
together

array([[  1,   2],
       [  3, 999],
       [  5,   6]])

In [16]:
#lets verify together is view or copy
a

array([[1, 2],
       [3, 4]])

In [17]:
#so togetehr is A COPY

### 2.Stack
- Stack a sequence of arrays along a new axis.

In [21]:
#lets create array
arrays=np.zeros((5,3,4))
arrays

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
#lets add random no with a mean of 3, and sd of 4
for n in range(5):
    arrays[n]=np.random.randn(3,4)
arrays

array([[[-0.09602591,  0.40291735,  0.41275709, -0.40181281],
        [ 0.37130212,  0.80084619,  0.17792995,  0.81236294],
        [ 0.51978414,  0.68246307, -1.42966161,  0.20090736]],

       [[ 0.31416621, -0.11113855,  0.56179031, -1.38039833],
        [-0.48996634, -0.09085299,  0.38109611, -0.22830622],
        [ 0.54621575,  0.48676908,  0.57757537,  0.67958853]],

       [[-0.04028869, -0.01890507,  1.97750399,  1.07818154],
        [-0.10450978,  1.20869537,  1.60245602, -2.25365803],
        [ 1.31539375,  0.411608  , -1.27389424,  1.37722907]],

       [[-1.76902494, -0.00566613,  1.47643408, -0.06979272],
        [ 0.63897387,  0.47286582, -1.52921279,  0.17470042],
        [ 0.80876819, -0.28709892, -0.50965191,  1.20056249]],

       [[ 0.94224726, -1.15059293,  0.52012421, -0.00579941],
        [-0.00927194,  0.9055793 , -0.35380701, -0.70197862],
        [-0.17423644,  1.19622514,  1.68966093, -0.72495918]]])

In [26]:
#above we got 5 2ds and each with 3 rows and 4 columns
#lets try stack
stack0=np.stack(arrays,axis=0)
stack1=np.stack(arrays,axis=1)
stack2=np.stack(arrays,axis=2)
stack0 #Contains all of the elements in oRIGINAL array

array([[[-0.09602591,  0.40291735,  0.41275709, -0.40181281],
        [ 0.37130212,  0.80084619,  0.17792995,  0.81236294],
        [ 0.51978414,  0.68246307, -1.42966161,  0.20090736]],

       [[ 0.31416621, -0.11113855,  0.56179031, -1.38039833],
        [-0.48996634, -0.09085299,  0.38109611, -0.22830622],
        [ 0.54621575,  0.48676908,  0.57757537,  0.67958853]],

       [[-0.04028869, -0.01890507,  1.97750399,  1.07818154],
        [-0.10450978,  1.20869537,  1.60245602, -2.25365803],
        [ 1.31539375,  0.411608  , -1.27389424,  1.37722907]],

       [[-1.76902494, -0.00566613,  1.47643408, -0.06979272],
        [ 0.63897387,  0.47286582, -1.52921279,  0.17470042],
        [ 0.80876819, -0.28709892, -0.50965191,  1.20056249]],

       [[ 0.94224726, -1.15059293,  0.52012421, -0.00579941],
        [-0.00927194,  0.9055793 , -0.35380701, -0.70197862],
        [-0.17423644,  1.19622514,  1.68966093, -0.72495918]]])

In [27]:
stack1 #Three two-dimensional arrays, each with five rows, and four columns

array([[[-0.09602591,  0.40291735,  0.41275709, -0.40181281],
        [ 0.31416621, -0.11113855,  0.56179031, -1.38039833],
        [-0.04028869, -0.01890507,  1.97750399,  1.07818154],
        [-1.76902494, -0.00566613,  1.47643408, -0.06979272],
        [ 0.94224726, -1.15059293,  0.52012421, -0.00579941]],

       [[ 0.37130212,  0.80084619,  0.17792995,  0.81236294],
        [-0.48996634, -0.09085299,  0.38109611, -0.22830622],
        [-0.10450978,  1.20869537,  1.60245602, -2.25365803],
        [ 0.63897387,  0.47286582, -1.52921279,  0.17470042],
        [-0.00927194,  0.9055793 , -0.35380701, -0.70197862]],

       [[ 0.51978414,  0.68246307, -1.42966161,  0.20090736],
        [ 0.54621575,  0.48676908,  0.57757537,  0.67958853],
        [ 1.31539375,  0.411608  , -1.27389424,  1.37722907],
        [ 0.80876819, -0.28709892, -0.50965191,  1.20056249],
        [-0.17423644,  1.19622514,  1.68966093, -0.72495918]]])

In [29]:
stack2 #Contains three two-dimensional arrays, each with four rows, and five columns.

array([[[-0.09602591,  0.31416621, -0.04028869, -1.76902494,
          0.94224726],
        [ 0.40291735, -0.11113855, -0.01890507, -0.00566613,
         -1.15059293],
        [ 0.41275709,  0.56179031,  1.97750399,  1.47643408,
          0.52012421],
        [-0.40181281, -1.38039833,  1.07818154, -0.06979272,
         -0.00579941]],

       [[ 0.37130212, -0.48996634, -0.10450978,  0.63897387,
         -0.00927194],
        [ 0.80084619, -0.09085299,  1.20869537,  0.47286582,
          0.9055793 ],
        [ 0.17792995,  0.38109611,  1.60245602, -1.52921279,
         -0.35380701],
        [ 0.81236294, -0.22830622, -2.25365803,  0.17470042,
         -0.70197862]],

       [[ 0.51978414,  0.54621575,  1.31539375,  0.80876819,
         -0.17423644],
        [ 0.68246307,  0.48676908,  0.411608  , -0.28709892,
          1.19622514],
        [-1.42966161,  0.57757537, -1.27389424, -0.50965191,
          1.68966093],
        [ 0.20090736,  0.67958853,  1.37722907,  1.20056249,
         -0

### 3.Split
- numpy.split(ary, indices_or_sections, axis=0)[source]¶
- Split an array into multiple sub-arrays. 
- splits evenly ie array elements should be divisble by 2

In [35]:
#lets create temp array
temp = np.arange(6)
#np.split(temp,0) causes error because you can split into 0 ararys
np.split(temp,1) # if it is 1 , it returns the same error


[array([0, 1, 2, 3, 4, 5])]

In [37]:
np.split(temp,2) # it

[array([0, 1, 2]), array([3, 4, 5])]

In [41]:
before_split=stack0
before_split.shape

(5, 3, 4)

In [42]:
s0=np.split(stack0,5,axis=0) #splitted stack into 5 3Ds
s0

[array([[[-0.09602591,  0.40291735,  0.41275709, -0.40181281],
         [ 0.37130212,  0.80084619,  0.17792995,  0.81236294],
         [ 0.51978414,  0.68246307, -1.42966161,  0.20090736]]]),
 array([[[ 0.31416621, -0.11113855,  0.56179031, -1.38039833],
         [-0.48996634, -0.09085299,  0.38109611, -0.22830622],
         [ 0.54621575,  0.48676908,  0.57757537,  0.67958853]]]),
 array([[[-0.04028869, -0.01890507,  1.97750399,  1.07818154],
         [-0.10450978,  1.20869537,  1.60245602, -2.25365803],
         [ 1.31539375,  0.411608  , -1.27389424,  1.37722907]]]),
 array([[[-1.76902494, -0.00566613,  1.47643408, -0.06979272],
         [ 0.63897387,  0.47286582, -1.52921279,  0.17470042],
         [ 0.80876819, -0.28709892, -0.50965191,  1.20056249]]]),
 array([[[ 0.94224726, -1.15059293,  0.52012421, -0.00579941],
         [-0.00927194,  0.9055793 , -0.35380701, -0.70197862],
         [-0.17423644,  1.19622514,  1.68966093, -0.72495918]]])]

In [43]:
type(s0)

list

In [46]:
s0[1].shape # 1 3D arary with 4 columns

(1, 3, 4)