In [6]:
import requests
import json

data = '{"query":"you are crazy"}'
response = requests.post('http://localhost:5007/conversations/default/parse', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')

{'next_action': 'utter_you_are_funny', 'tracker': {'events': None, 'latest_event_time': 1531244607.39518, 'latest_message': {'entities': [], 'intent': {'confidence': 0.08761521495558904, 'name': 'you_are_funny'}, 'intent_ranking': [{'confidence': 0.08761521495558904, 'name': 'you_are_funny'}, {'confidence': 0.05068440071638937, 'name': 'oops'}, {'confidence': 0.04876113393137155, 'name': 'are_you_sure'}, {'confidence': 0.041089456672713055, 'name': 'you_are_clever'}, {'confidence': 0.0397788854869823, 'name': 'how_are_you'}, {'confidence': 0.036715485964918304, 'name': 'are_you_busy'}, {'confidence': 0.03393178635356233, 'name': 'you_are_bad'}, {'confidence': 0.030676618635937368, 'name': 'you_are_right'}, {'confidence': 0.02880130591299356, 'name': 'you_are_beautiful'}, {'confidence': 0.028795971516330298, 'name': 'you_are_welcome'}], 'text': 'you are crazy'}, 'paused': False, 'sender_id': 'default', 'slots': {'location': None}}}
-----------------------------


In [3]:
import requests
import json

data = '{"query":"can you help me"}'
response = requests.post('http://localhost:5007/conversations/default/respond', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')
# print (json_response[0]['text'])

[{'recipient_id': 'default', 'text': 'Thank you for the complement'}]
-----------------------------


In [ ]:
import requests
import json

data = '{"query":"hi"}'
response = requests.post('http://localhost:5006/conversations/default/respond', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')

In [39]:
import requests
import json

data = '{"query":"Tell me the weather"}'
response = requests.post('http://localhost:5008/conversations/default/respond', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')
print (json_response[0]['text'])

[{'recipient_id': 'default', 'text': 'In what location?'}]
-----------------------------
In what location?


In [43]:
import requests
import json

data = '{"query":"in London"}'
response = requests.post('http://localhost:5008/conversations/default/respond', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')
print (json_response[0]['text'])

[{'recipient_id': 'default', 'text': 'It is currently Sunny in London at the moment.The temperature is 18.0 degrees,\n                        the humidity is 68 % and the wind speed is 0.0 mph'}]
-----------------------------
It is currently Sunny in London at the moment.The temperature is 18.0 degrees,
                        the humidity is 68 % and the wind speed is 0.0 mph


In [44]:
import requests
import json

data = '{"query":"bye"}'
response = requests.post('http://localhost:5008/conversations/default/respond', data=data)
json_response = response.json()
print(json_response)
print('-----------------------------')
print (json_response[0]['text'])

[{'recipient_id': 'default', 'text': 'Talk to you later.'}]
-----------------------------
Talk to you later.


In [9]:
import requests
# importing the requests library
import requests
 
# api-endpoint
URL = "http://localhost:5006/conversations/default/respond"
 
# location given here
query = "hi"
 
# defining a params dict for the parameters to be sent to the API
PARAMS = {'query':query}
 
# sending get request and saving the response as response object
r = requests.post(url = URL, params = PARAMS)

# extracting data in json format
data = r.text
data

'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>The browser (or proxy) sent a request that this server could not understand.</p>\n'

### Tracker

In [50]:
import requests
import json


response = requests.get('http://localhost:5008/conversations/default/tracker')
json_response = response.json()
# print(json_response)
print(json.dumps(json_response, indent=4, sort_keys=True))
print('-----------------------------')
# print (json_response[0]['text']) #1530978408.041418

{
    "events": [
        {
            "event": "action",
            "name": "action_listen",
            "timestamp": 1530978408.041418
        },
        {
            "event": "user",
            "parse_data": {
                "entities": [],
                "intent": {
                    "confidence": 0.8578820695798579,
                    "name": "greet"
                },
                "intent_ranking": [
                    {
                        "confidence": 0.8578820695798579,
                        "name": "greet"
                    },
                    {
                        "confidence": 0.09304040236444858,
                        "name": "inform"
                    },
                    {
                        "confidence": 0.04907752805569354,
                        "name": "goodbye"
                    }
                ],
                "text": "hi"
            },
            "text": "hi",
            "timestamp": 1530978408.057278
        },
  

### all conversations

In [51]:
import requests
import json

response = requests.get('http://localhost:5008/conversations')
json_response = response.json()
# print(json_response)
print(json.dumps(json_response, indent=4, sort_keys=True))

[
    "default"
]


In [1]:
byte1= b'\xc2\xc9'
byte1

b'\xc2\xc9'

bytes

In [5]:
tuple1=(1,2,3)
tuple1.

AttributeError: 'tuple' object has no attribute 'max'

In [1]:
[ chr(i) for i in [65, 66, 67] ] 

['A', 'B', 'C']

In [2]:
{ ord(i) for i in 'apple' }

{97, 101, 108, 112}

In [3]:
type(id)

builtin_function_or_method

In [4]:
x=10
id(x)

4534470256

In [5]:
y=id(x)
y

4534470256

In [7]:
k=[print(i) for i in "maverick" if i not in "aeiou"]

m
v
r
c
k


In [8]:
k #list has all nones *********

[None, None, None, None, None]

In [9]:
{0 if i%2 ==0 else 1 for i in range(8)}

{0, 1}

In [10]:
class Animal:
    'class doc'
    def __init__(self,name):
        'func doc'
        self.name=name
a = Animal('hello')
print(a.name)

hello


In [11]:
help(Animal)

Help on class Animal in module __main__:

class Animal(builtins.object)
 |  class doc
 |  
 |  Methods defined here:
 |  
 |  __init__(self, name)
 |      func doc
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [13]:
class A:
    def __init__(self):
        print('one')

    def f(self):
        print(float())
        print(hex(-255))

class B(A):
    def __init__(self):
        print('two')

    def f(self):
        print(float())
        print(hex(-42))

In [1]:
###Next handson
#4.1

In [ ]:
Define the class Point that represents x, y, and z coordinates of 3D coordinate system.

Hint : Define the initializer method, __init__ that takes three values and assigns them to attributes x, y and z respectively.
Now create an object p1 = Point(4, 2, 9) and print it using the statement print(p1). You may type python3.5 to use the latest version for the exercise

In [5]:
class Point:
    def __init__(self,*args):
        self.x=args[0]
        self.y=args[1]
        self.z=args[2]
#     def __str__(self):
#         return 'x is {}'.format(self.x)
p1=Point(4,2,9)
print(p1)

x is 4


In [ ]:
#4.2 - using __str__
object should print - point : (x, y, z

In [6]:
class Point:
    def __init__(self,*args):
        self.x=args[0]
        self.y=args[1]
        self.z=args[2]
    def __str__(self):
        return 'point: ({},{},{})'.format(self.x,self.y,self.z)
p1=Point(4,2,9)
print(p1)

point: (4,2,9)


In [ ]:
#4.3
determine distance between two point objects
distance = sqrt( (x1-x2)**2 + (y1-y2)**2 + (z1 -z2)**2 ).

In [10]:
from math import sqrt 
class Point:
    def __init__(self,*args):
        self.x=args[0]
        self.y=args[1]
        self.z=args[2]
    def __str__(self):
        return 'point: ({},{},{})'.format(self.x,self.y,self.z)
    
def distance(p1,p2):
    return sqrt( (p1.x-p2.x)**2 + (p1.y-p2.y)**2 + (p1.z -p2.z)**2 )
    
p1=Point(4,5,6)
p2=Point(-2,-1,4)
print(distance(p1,p2))

8.717797887081348


In [ ]:
#4.4 use + on object addition override __add__

In [11]:
class Point:
    def __init__(self,*args):
        self.x=args[0]
        self.y=args[1]
        self.z=args[2]
    def __str__(self):
        return 'point: ({},{},{})'.format(self.x,self.y,self.z)
    def __add__(self, otherPObj):
        return Point(self.x+otherPObj.x, self.y+otherPObj.y,self.z+otherPObj.z)
    
p1=Point(1,2,3)
p2=Point(2,3,4)

print(p1+p2)


point: (3,5,7)


In [1]:
#5.1
list1=[1,2,3]
x=iter(list1)

In [5]:
next(x)

StopIteration: 

In [6]:
class A:
    x = 0

    def __init__(self, a, b):
        self.a = a
        self.b = b
        A.x += 1

    def __init__(self):
        A.x += 1

    def displayCount(self):
        print('Count : %d' % A.x)

    def display(self):
        print('a :', self.a, ' b :', self.b)

a1 = A('George', 25000)
a2 = A('John', 30000)
a3 = A()
a1.display()
a2.display()
print(A.x)

TypeError: __init__() takes 1 positional argument but 3 were given

In [7]:
{i:j for i in "abcd" for j in "kiwi"}

{'a': 'i', 'b': 'i', 'c': 'i', 'd': 'i'}

In [9]:
'itertools.dropwhile(lambda x: x<5, [1,4,6,4,1])'

'itertools.dropwhile(lambda x: x<5, [1,4,6,4,1])'

In [1]:
class A:

    def __init__(self, val):
        self.x = val

    @property
    def x(self):
        return self.__x

    @x.setter
    def x(self, val):
        self.__x = val
        
    @x.deleter
    def x(self):
        del self.__x

a = A(7)
del a.x
print(a.x)

AttributeError: 'A' object has no attribute '_A__x'

In [2]:
from abc import ABC, abstractmethod

class A(ABC):

    @abstractmethod
    def m1(self):
        print('In class A, Method m1.')

class B(A):

    @staticmethod
    def m1(self):
        print('In class B, Method m1.')

b = B()
B.m1(b)

In class B, Method m1.


In [3]:
import re

In [4]:
re.sub(r'[aeiou]', 'X', 'abcdefghij')

'XbcdXfghXj'

In [5]:
from abc import ABC, abstractmethod

class A(ABC):

    @classmethod
    @abstractmethod
    def m1(self):
        print('In class A, Method m1.')

class B(A):

    @classmethod
    def m1(self):
        print('In class B, Method m1.')

b = B()
b.m1()
B.m1()
A.m1()

In class B, Method m1.
In class B, Method m1.
In class A, Method m1.


In [6]:
class A:

    @staticmethod
    def m1(self):
        print('Static Method')

    @classmethod
    def m1(self):
        print('Class Method')

A.m1()

Class Method


In [7]:
class A:

    def __init__(self, val):
        self.x = val

    @property
    def x(self):
        return self.__x

    @x.setter
    def x(self, val):
        self.__x = val
        
    @x.deleter
    def x(self):
        del self.__x

a = A(7)
del a.x
print(a.x)

AttributeError: 'A' object has no attribute '_A__x'

In [8]:
from abc import ABC, abstractmethod

class A(ABC):

    @abstractmethod
    @classmethod
    def m1(self):
        print('In class A, Method m1.')

class B(A):

    @classmethod
    def m1(self):
        print('In class B, Method m1.')

b = B()
b.m1()
B.m1()
A.m1()

AttributeError: attribute '__isabstractmethod__' of 'classmethod' objects is not writable

In [9]:
def outer(x, y):

    def inner1():
        return x+y

    def inner2(z):
        return inner1() + z

    return inner2


f = outer(10, 25)

print(f(15))

50


In [11]:
class A:

    @staticmethod
    @classmethod
    def m1(self):
        print('Hello')

A.m1(5)

TypeError: 'classmethod' object is not callable

In [12]:
f = open('temp.txt')


In [13]:
def s1(x, y):
    return x*y

class A:

    @staticmethod
    def s1(x, y):
        return x + y

    def s2(self, x, y):
        return s1(x, y)

a = A()
print(a.s2(3, 7))

21


In [14]:
tupl=(1,2,3,4,5,6)
tupl[:]

(1, 2, 3, 4, 5, 6)

In [17]:
tupl[2:3]

(3,)

In [5]:
t_tuple=(1,2,3,4,5,6,7,(8,9))
t_tuple[0::2]

(1, 3, 5, 7)

In [6]:
t_tuple[4:2:-1]

(5, 4)

In [8]:
t_tuple[7][1]

9

In [10]:
sl = slice(1,4,2)
t_tuple[sl]

(2, 4)

In [37]:
s=range(-5)
list(s)


[]

In [40]:
s=range(11)
tuple(s)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [42]:
s=range(10,-1,-1)
tuple(s)

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

In [1]:
dict_={}
type(dict_)

dict

In [2]:
dict_=dict()
type(dict_)

dict

In [3]:
my_dict={'k1':'v1','k2':'v2','k3':'v3'}
my_dict

{'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}

In [4]:
my_dict['k4']='v4'
my_dict

{'k1': 'v1', 'k2': 'v2', 'k3': 'v3', 'k4': 'v4'}

In [5]:
del my_dict['k4']

In [13]:
k=my_dict.keys()

In [14]:
v=my_dict.values()

In [15]:
for key in my_dict:
    print('{} - {}'.format(key,my_dict[key]))

k1 - v1
k2 - v2
k3 - v3


In [20]:
new_dict1=zip(k,v)
new_dict=dict(new_dict1)
new_dict

{'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}

In [21]:
new_dict3=new_dict.copy()
new_dict3

{'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}

In [22]:
new_dict3.clear()

In [23]:
comp=[x for x in range(5)]

In [24]:
comp

[0, 1, 2, 3, 4]

In [1]:
comp={dict(k,v for k in r)}

SyntaxError: Generator expression must be parenthesized if not sole argument (<ipython-input-1-c2c83f24abf6>, line 1)

In [12]:
class Circle:
    no_of_circle_instance=0
    
    def __init__(self,radius):
        self._radius=radius
        Circle.no_of_circle_instance+=1
        
    def getCicrcleCount(self):
        return Circle.no_of_circle_instance
    
c=Circle(20)
c.getCicrcleCount()
c1=Circle(40)
c1.getCicrcleCount()

Circle.getCicrcleCount(c1)
#to get Circle object count, you have to apss c1 object ..which does not make sense
#as circle count belongs to other objects also

2

In [3]:
def hello():
    print('I will be printed only after calling \'next\' ')
    name=yield
    print('Sent name1 is ',name)
    name2=yield
    print('sent name2 is',name2)
    name3=yield
    print('sent name3 is',name3)
    yield

s=hello() #- ##Wont print anything since fun body has yield keyword
#next(s)
s.send('jinka')
s.send('syam') #- prints - sent name2 is syam
s.send('kumar')

TypeError: can't send non-None value to a just-started generator

In [9]:
def cor(tokenid=0):
    try:
        
        while True:
            input = yield
            tokenid+=1
            print(f'{input} token id {tokenid}')
    except GeneratorExit:
        print(f'last issued token id is {tokenid}')
        
s= cor(100)
next(s)


In [10]:
s.send('syam')

syam token id 101


In [11]:
s.send('kumar')

kumar token id 102


In [12]:
s.close()

last issued token id is 102


In [2]:
def exec_(x):
    if x>2:
        raise TypeError('it should be lessa than 2')
    else:
        print('good')
def main():
    try:
        exec_(3)
    except TypeError as e:
        print(f'error is {e}')
main()

error is it should be lessa than 2


In [17]:
class custom_excetion(Exception):
    def __init__(self, value):
        self._value=value
    def __str__(self):
        return str(self._value)



In [18]:
try:
    a=2,
    b='hello'
    if not (isinstance(a, int) and isinstance(b,int)):
        raise custom_excetion('Two Inputs must be integers')
    c=a**b
except custom_excetion as e:
    print(e)

Two Inputs must be integers


In [20]:
import sqlite3
try:
    con = sqlite3.connect('test.db')
    cursor= con.cursor()
    '''
    sample code
    '''
except exception as e:
    print('error while create db')
finally:
    con.close()


In [26]:
import sqlite3
class DbConnect(object):
    def __init__(self, value):
        self.dbname=value
    def __enter__(self):
        self.db = sqlite3.connect(self.dbname)
        return self.db
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.db.close()
with DbConnect('Test.db') as db:
    cus= db.cursor()

In [24]:
help(__exit__)

NameError: name '__exit__' is not defined

In [27]:
import sys

def main():
    v=sys.version_info
    print('{}.{}.{}'.format(*v))

main()

SyntaxError: invalid character in identifier (<ipython-input-27-f00cf1c8cff0>, line 4)

In [32]:
import sys
c=sys.version_info
print(*c)

3 6 4 final 0


In [33]:
import sys
c=sys.platform
c

'darwin'

In [37]:
import os
s=os.getcwd()
s

'/Users/syamkumarj/Documents/Workspace/python_anaconda_workspace'

In [1]:
import numpy as np

*hello

_hello

_hello

*helllo*

_hello_

hello

**hello**

__hello__

*hello*

**hello**

* hello
    * i am 

1. hello
    1.1. hello

- **Fruit Types**
    - **Berries**
        + Blue
        * Berry
        - s
        - s
    - **Citrus**

In [1]:
import numpy as np

In [2]:
l=[-17,-4,0,2,21,37,105]
s=np.array(l)

In [3]:
s[0]

-17

In [4]:
s[0]=122
s

array([122,  -4,   0,   2,  21,  37, 105])

In [5]:
s[-1]

105

In [6]:
s.size

7

In [9]:
s[4%2]

122

In [10]:
s=np.arange(35).reshape(7,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [11]:
s[0]

array([0, 1, 2, 3, 4])

In [12]:
s[0,1]

1

In [13]:
s[0][1]

1

In [14]:
s=np.arange(70).reshape(2,7,5)
s

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [15]:
s[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
s[0][1]

array([5, 6, 7, 8, 9])

In [17]:
s[0][1][2]

7

In [18]:
import numpy as np

In [21]:
s=[1,2,3]
s=np.array(s)
s1=[True,False,True]
s2=s[s1]
s2

array([1, 3])

In [26]:
s=np.array([2,3,4,6,9,13,16,21,25,26,30])
s

array([ 2,  3,  4,  6,  9, 13, 16, 21, 25, 26, 30])

In [31]:
bool_mask=0==(s%3)
bool_mask


array([False,  True, False,  True,  True, False, False,  True, False,
       False,  True])

In [29]:
bool_mask1=s[bool_mask]
bool_mask1

array([4, 2, 3, 2, 2, 3, 3, 2, 3, 4, 2])

In [32]:
my_vector = np.array([-17,-4,0,2,21,37,105])
bool_mask=[0==(my_vector % 7)]
bool_mask

[array([False, False,  True, False,  True, False,  True])]

In [40]:
s=my_vector[bool_mask]
s

array([  0,  21, 105])

In [43]:
s1=s[s>0]

In [44]:
s1

array([ 21, 105])

In [50]:
base_array=np.array([[0,2,3,4,6,9,13,16,21,25,26,30]])
req_array=0==(base_array % 3)
req_array

array([[ True, False,  True, False,  True,  True, False, False,  True,
        False, False,  True]])

In [52]:
req_array1=base_array[req_array]
req_array1

array([ 0,  3,  6,  9, 21, 30])

In [53]:
req_array1[req_array1>0]

array([ 3,  6,  9, 21, 30])

In [2]:
import numpy as np

x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [5]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
import numpy as np

x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [8]:
import numpy as np

x = np.arange(90).reshape(3, 15, 2)

In [9]:
import numpy as np

x = np.arange(20).reshape(10, 10)

ValueError: cannot reshape array of size 20 into shape (10,10)

In [10]:
import numpy as np

x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [11]:
import numpy as np

x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [12]:
import numpy as np

x = np.arange(4).reshape(2,2)

y = np.vsplit(x,2)
print(y[0])

[[0 1]]


In [13]:
import numpy as np

x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [14]:
import numpy as np

x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [15]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [16]:
x = np.arange(4)
print(x**2)

[0 1 4 9]


In [17]:
import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [18]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [19]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [20]:
import numpy as np

x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [21]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [22]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [23]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [24]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [25]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [26]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]


In [27]:
import nupy as np

print(np.array(([1, 2], (3,4))).shape)

ModuleNotFoundError: No module named 'nupy'

In [28]:
np.random.rand(3, 2)

array([[0.44271259, 0.97653309],
       [0.53546391, 0.32591208],
       [0.13386906, 0.03901382]])

In [29]:
np.random.random(3, 2)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [30]:
import numpy as np

print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [3]:
s='Get me the data for PC999 product class'
text='PC999 product class'
s1=s.find(text)
print('start - ',s1 )
s2=s1+len(text)
print('end - ',s2)
print(s[s1:s2])

start -  20
end -  39
PC999 product class


In [9]:
s='pc999 product class'
text='pc999 product class'
s1=s.find(text)
print('start - ',s1 )
s2=s1+len(text)
print('end - ',s2)
print(s[s1:s2])

start -  0
end -  19
pc999 product class
