In [8]:
import pandas as pd
import numpy as np

In [9]:
pd.Series([1,2,3,np.nan,4],name='mydata',dtype='float64')

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
Name: mydata, dtype: float64

In [10]:
pd.Series(data=[50,20,30,40],index=['Q1\'16','Q2\'16','Q3\'16','Q4\'16'],name='Product dales',dtype='int64')

Q1'16    50
Q2'16    20
Q3'16    30
Q4'16    40
Name: Product dales, dtype: int64

In [11]:
my_index=pd.date_range('Jul2016',periods=6,freq='MS',name='mytime')
my_index

DatetimeIndex(['2016-07-01', '2016-08-01', '2016-09-01', '2016-10-01',
               '2016-11-01', '2016-12-01'],
              dtype='datetime64[ns]', name='mytime', freq='MS')

In [12]:
my_data=np.array(np.arange(24)).reshape(6,4)
my_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
my_dataframe=pd.DataFrame(index=my_index,data=my_data,columns=list('ABCD'),dtype='int64')
my_dataframe

A   B   C   D
mytime                    
2016-07-01   0   1   2   3
2016-08-01   4   5   6   7
2016-09-01   8   9  10  11
2016-10-01  12  13  14  15
2016-11-01  16  17  18  19
2016-12-01  20  21  22  23

In [14]:
my_dataframe=pd.DataFrame({
    'float':1.0,
    'series':pd.Series([3]*4,index=['a','b','c','d']),
    'array':np.arange(4),
    'categories':pd.Categorical(['test','t','e','s']),
    'dull':'my dull data'
    
})
my_dataframe

array categories          dull  float  series
a      0       test  my dull data    1.0       3
b      1          t  my dull data    1.0       3
c      2          e  my dull data    1.0       3
d      3          s  my dull data    1.0       3

In [15]:
my_dataframe.dtypes

array            int64
categories    category
dull            object
float          float64
series           int64
dtype: object

In [16]:
my_dataframe.values

array([[0, 'test', 'my dull data', 1.0, 3],
       [1, 't', 'my dull data', 1.0, 3],
       [2, 'e', 'my dull data', 1.0, 3],
       [3, 's', 'my dull data', 1.0, 3]], dtype=object)

In [17]:
my_dataframe.columns

Index(['array', 'categories', 'dull', 'float', 'series'], dtype='object')

In [18]:
my_dataframe.describe()

array  float  series
count  4.000000    4.0     4.0
mean   1.500000    1.0     3.0
std    1.290994    0.0     0.0
min    0.000000    1.0     3.0
25%    0.750000    1.0     3.0
50%    1.500000    1.0     3.0
75%    2.250000    1.0     3.0
max    3.000000    1.0     3.0

In [19]:
my_dataframe

array categories          dull  float  series
a      0       test  my dull data    1.0       3
b      1          t  my dull data    1.0       3
c      2          e  my dull data    1.0       3
d      3          s  my dull data    1.0       3

In [20]:
my_dataframe.T

a             b             c             d
array                  0             1             2             3
categories          test             t             e             s
dull        my dull data  my dull data  my dull data  my dull data
float                  1             1             1             1
series                 3             3             3             3

In [21]:
my_dataframe.sort_index(axis=1,ascending=False)

series  float          dull categories  array
a       3    1.0  my dull data       test      0
b       3    1.0  my dull data          t      1
c       3    1.0  my dull data          e      2
d       3    1.0  my dull data          s      3

In [22]:
my_dataframe.sort_values(by='array',ascending=False)

array categories          dull  float  series
d      3          s  my dull data    1.0       3
c      2          e  my dull data    1.0       3
b      1          t  my dull data    1.0       3
a      0       test  my dull data    1.0       3

In [23]:
my_date_index=pd.date_range('July2016',periods=6,freq='MS',name='mytime')
my_date_index

DatetimeIndex(['2016-07-01', '2016-08-01', '2016-09-01', '2016-10-01',
               '2016-11-01', '2016-12-01'],
              dtype='datetime64[ns]', name='mytime', freq='MS')

In [24]:
sample_data=np.array(np.arange(24)).reshape(6,4)
sample_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
sample_df=pd.DataFrame(data=sample_data,index=my_date_index,columns=list('ABCD'),dtype='int64')
sample_df

A   B   C   D
mytime                    
2016-07-01   0   1   2   3
2016-08-01   4   5   6   7
2016-09-01   8   9  10  11
2016-10-01  12  13  14  15
2016-11-01  16  17  18  19
2016-12-01  20  21  22  23

In [26]:
sample_df[0:2]

A  B  C  D
mytime                
2016-07-01  0  1  2  3
2016-08-01  4  5  6  7

In [27]:
sample_df['C']

mytime
2016-07-01     2
2016-08-01     6
2016-09-01    10
2016-10-01    14
2016-11-01    18
2016-12-01    22
Freq: MS, Name: C, dtype: int64

In [28]:
sample_df.loc['2016-07-01':'2016-08-01']

A  B  C  D
mytime                
2016-07-01  0  1  2  3
2016-08-01  4  5  6  7

In [30]:
pd.Series(data=[1,2,3],name='mydata',index=['1','2','3'])

1    1
2    2
3    3
Name: mydata, dtype: int64

In [42]:
dates_index=pd.date_range('Jan2016',periods=6,freq='MS')
dates_index

DatetimeIndex(['2016-01-01', '2016-02-01', '2016-03-01', '2016-04-01',
               '2016-05-01', '2016-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [43]:
np_data=np.array(np.arange(24)).reshape(6,4)

In [44]:
my_df=pd.DataFrame(data=np_data,index=dates_index,columns=list('ABCD'))
my_df

A   B   C   D
2016-01-01   0   1   2   3
2016-02-01   4   5   6   7
2016-03-01   8   9  10  11
2016-04-01  12  13  14  15
2016-05-01  16  17  18  19
2016-06-01  20  21  22  23

In [47]:
my_df['C']

2016-01-01     2
2016-02-01     6
2016-03-01    10
2016-04-01    14
2016-05-01    18
2016-06-01    22
Freq: MS, Name: C, dtype: int64

In [48]:
my_df[0:3]

A  B   C   D
2016-01-01  0  1   2   3
2016-02-01  4  5   6   7
2016-03-01  8  9  10  11

In [55]:
my_df.loc['2016-01-01']

A    0
B    1
C    2
D    3
Name: 2016-01-01 00:00:00, dtype: int64

In [65]:
my_df['fruits']=['apple','orange','bananas','strawberry','a','b']
my_df

A   B   C   D      fruits
2016-01-01   0   1   2   3       apple
2016-02-01   4   5   6   7      orange
2016-03-01   8   9  10  11     bananas
2016-04-01  12  13  14  15  strawberry
2016-05-01  16  17  18  19           a
2016-06-01  20  21  22  23           b

In [70]:
my_df[my_df['fruits'].isin(['apple'])]

A  B  C  D fruits
2016-01-01  0  1  2  3  apple

In [73]:
my_df['fruits']=['apple','orange','bananas','strawberry','a','b']

In [74]:
n_data=np.array(np.arange(6))

In [75]:
my_df['extra']=n_data

In [76]:
my_df

A   B   C   D      fruits  extra
2016-01-01   0   1   2   3       apple      0
2016-02-01   4   5   6   7      orange      1
2016-03-01   8   9  10  11     bananas      2
2016-04-01  12  13  14  15  strawberry      3
2016-05-01  16  17  18  19           a      4
2016-06-01  20  21  22  23           b      5

In [82]:
my_df.at['2016-02-01',['A','B']]=244

In [83]:
my_df

A    B    C   D      fruits  extra
2016-01-01    0    1    2   3       apple      0
2016-02-01  244  244    6   7      orange      1
2016-03-01    8    9  444  11     bananas      2
2016-04-01   12   13   14  15  strawberry      3
2016-05-01   16   17   18  19           a      4
2016-06-01   20   21   22  23           b      5

In [81]:
my_df.iat[2,2]=444
my_df

A   B    C   D      fruits  extra
2016-01-01    0   1    2   3       apple      0
2016-02-01  244   5    6   7      orange      1
2016-03-01    8   9  444  11     bananas      2
2016-04-01   12  13   14  15  strawberry      3
2016-05-01   16  17   18  19           a      4
2016-06-01   20  21   22  23           b      5