# Rearranging array elements
- fliplr
- flipud
- roll
- rot90

In [1]:
import numpy as np
my_start_array= np.array(np.arange(24))
my_3_8_array=my_start_array.reshape((3,8))
my_2_3_4_array=my_start_array.reshape((2,3,4))

### 1.fliplr "Flip left right"

Flip an array in the left or right direction

- Flip the entries in each row in the left/right direction. <b>Columns are preserved, but appear in a different order than before.</b>
- Input must be >= 2-d
- the flipping takes place over the last axis..very imp


In [10]:
#np.fliplr(my_start_array) fails
#since Input must be >= 2-d

In [3]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [4]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [6]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

### 2.flipud
- flip up down


In [8]:
np.flipud(my_3_8_array)
#if you see below first row became last and last became first

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [9]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### 3.roll
- numpy.roll(a, shift, axis=None)
- Roll array elements along a given axis.
- Elements that roll beyond the last position are re-introduced at the first.


In [12]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
#apply roll 
np.roll(my_start_array,5) # here first 5 elements are rolled to next
#and the last 5 came to first

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [17]:
#We can use negative parameter
#what happens is instead of last 5..immediate next 5 will come first and first 5 will go to last

In [20]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [19]:
#roll can also be used on multi D
np.roll(my_3_8_array,1)
#below first element moved by 1 position and last element came to first
#unlike 1D 

array([[23,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22]])

In [21]:
#same like above we can use negative
np.roll(my_3_8_array,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23,  0]])

### 4.ROT 90 
- Rotate 90 degrees
- The elements that were formerly in the first row are now in the first column, but they're displayed in descending order.
- As a little bit of background, if you studied trigonometry, you'll know that counter clockwise rotations are positive degrees and clockwise rotations are negative degrees.

In [23]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [24]:
#k=1 is clock wise positive
#k=-1 is anticlock
np.rot90(my_3_8_array,k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])