# Transpose like operations

- transpose
- swap axes
- roll axes
- use np.transpose to permute all the axis at once. 
- use np.swapaxes to swap any two axes.
- use np.rollaxis to rotate over the axes. 

In [1]:
import numpy as np
my_start_array= np.array(np.arange(24))
my_3_8_array=my_start_array.reshape((3,8))
my_2_3_4_array=my_start_array.reshape((2,3,4))

### 1.transpose


In [2]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
np.transpose(my_start_array) #since it is 1D no change 1x1 T is 1x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
#lets apply on 2D
np.transpose(my_3_8_array)#rows and colummns are exchanged
#ie i,j will become j,i

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [6]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [10]:
#lets try using axis
#lets take a tupple and in this case, I'm going to use zero, two and one as the elements of the tupple. What this does is it transposes along the axis indexed by two and the axis indexed by one.
np.transpose(my_3_8_array,axes=(1,0)) #here 0 axis is rows ie 3 ,1 is colun axis ie 8 now that
#we have 1,0 it becomes 8x3

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [12]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
#on 3D
np.transpose(my_2_3_4_array,axes=(0,2,1))
#ie 2(0)x4(1)x3(2) became 2(0)x3(2)x4(1)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

### swapaxes
- Interchange two axes of an array.
- returns - 
-     For NumPy >= 1.10.0, if a is an ndarray, then a view of a is returned; otherwise a new array is created.
-     For earlier NumPy versions a view of a is returned only if the order of the axes is changed, otherwise the input array is returned.

In [15]:
#The documentation tells us that for NumPy versions greater than 1.1.0,
#if a is an nvarray, then a view of a is returned. Otherwise, a new array is created, 
#in other words a copy is created. For earlier NumPy versions, 
#a view of a is returned only if the order of the axis is changed.

In [16]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
np.swapaxes(my_2_3_4_array,2,0) #means 012 is 234 so 432

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### 3.rollaxes
- numpy.rollaxis(a, axis, start=0)
- Roll the specified axis backwards, until it lies in a given position.
- we should use moveaxis now

In [20]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
np.rollaxis(my_2_3_4_array,1,0) #234 became 324

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])