In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.14.0


In [6]:
p_list=list([1,2,3,4])
type(p_list)

list

In [7]:
p_list

[1, 2, 3, 4]

In [8]:
np_list=np.array(p_list)
type(np_list)
np_list

array([1, 2, 3, 4])

- python array print came as a list 
- but numpy array it came as array([list])

#### arithmetic operations on Array

In [9]:
np_list2=np.array([5,6,7,8])
np_list+np_list2

array([ 6,  8, 10, 12])

##### creating numpy array from a tuple

In [10]:
p_tuple=(1,2,3,4)
np_list3=np.array(p_tuple)
np_list3

array([1, 2, 3, 4])

##### promotion of data types

In [11]:
p_tuple=(14,-3.34,(5+7j))
np_list4=np.array(p_tuple)
np_list4

array([14.  +0.j, -3.34+0.j,  5.  +7.j])

In [12]:
p_tuple=(14,'-3.34',(5+7j))
np_list4=np.array(p_tuple)
np_list4

array(['14', '-3.34', '(5+7j)'], dtype='<U21')

##### Difference between numpy and python data structure

- \* works differently in python & numpy
- in python it works as replication factor
- but in numpy it works like a multiplcation

In [14]:
my_tuple=(1,2,3) 
np_array=np.array(my_tuple)

In [15]:
my_tuple*8

(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)

In [16]:
np_array*8

array([ 8, 16, 24])

--

In [4]:
import numpy as np



a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], 

     [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]

x = np.array(a, dtype='float64')

print(type(x))
print(x.ndim)
print(x.shape)
print(x)

<class 'numpy.ndarray'>
3
(2, 3, 2)
[[[4.1 2.5]
  [1.1 2.3]
  [9.1 2.5]]

 [[8.6 9.9]
  [3.6 4.3]
  [6.6 0.3]]]
