# Views and Copies

In [2]:
import numpy as np

In [3]:
mi_casa=np.array([-45,-31,-12,0,2,25,51,99])

In [4]:
su_casa=mi_casa

### Are both same?

In [5]:
su_casa is mi_casa

True

In [6]:
id(su_casa)

4351386768

In [7]:
id(mi_casa)

4351386768

In [8]:
#value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
#change a value
su_casa[4]=1010
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [10]:
#there is impact
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [11]:
#create a new variable
tree_house=np.array([-45,-31,-12,0,1010,25,51,99])

In [12]:
#tree house has same elements as that of mi_casa
#lets test both are same?
tree_house==mi_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

### Is it same?

In [13]:
tree_house is mi_casa

False

In [14]:
id(tree_house)

4370393088

In [15]:
id(mi_casa)

4351386768

In [16]:
#So even though both have same values but
#they refer to different memory locations


## Views: A shallow copy

In [17]:
#a View created by using view() method on an array
farm_house=tree_house.view()
#farm_house.shape=(2,4)

In [18]:
tree_house #It is 1 DIMENSIONAL

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [19]:
farm_house #IT IS 2 Dimensional

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

### Are these connected?

In [20]:
tree_house[1]=200

In [21]:
farm_house

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

In [22]:
#changes got reflected
#so elements of view and array are located at the same memory location

In [23]:
id(tree_house)

4370393088

In [24]:
id(farm_house)

4370471312

In [25]:
tree_house is farm_house 
#gives you false bcoz one is 1D and other is 2d or 1d it wont be the same


False

In [26]:
#we can also make view into multi dimensional
farm_house.shape=(2,4)
farm_house

array([[ -45,  200,  -12,    0],
       [1010,   25,   51,   99]])

In [27]:
#share different memory locations but are connected"
test_array=np.array([1,2,3,4])
test_view=test_array.view()
print(id(test_array))
print(id(test_view))

4370472112
4370499824


In [33]:
tree_house

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

In [35]:
farm_house[0][1]=600
tree_house

array([ -45,  600,  -12,    0, 1010,   25,   51,   99])

 so even view turns into a n dim, if you update an element in view ,  
 master also gets the change  
but if you reshape view, master wont get effected  

### Deep Copy

In [28]:
#Deep copy created by using copy function
dog_house=np.copy(tree_house)

In [29]:
#lets modify and see
dog_house[0]=-121
#dog_house.shape=(2,4)
#dog_house
#we can make it into multi D

In [30]:
tree_house

array([ -45,  200,  -12,    0, 1010,   25,   51,   99])

In [31]:
#so both are in different memory locations when we use deep copy

In [32]:
#Thats the difference between Views and Copy
#views share same memory location ie provides multiple references to same memory location
#copy as name says copied to a new memory location ie duplicates data into different memory locations