### Basic Operations with Scalars

- Operations in Numpy are carried out element wise.
- Hence the expression x + 10, increases every element of array x by 10.

In [2]:
import numpy as np



x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
print(x + 10, end='\n\n')


[[10 11 12]
 [13 14 15]]



In [4]:
print(x * 3, end='\n\n')


[[ 0  3  6]
 [ 9 12 15]]



In [5]:
print(x % 2)

[[0 1 0]
 [1 0 1]]


### Basic Operations between Arrays
- happens element wise

In [6]:
import numpy as np

x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])


print(x + y, end='\n\n')
print(x * y)

[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]
