### Try 1

Write the statement to import numpy package as np.

Define the list n = [5, 10, 15, 20, 25].

Create a numpy array x, using array method of numpy package.

Hint : Pass list n as argument to array method.
Determine the type of array x.

Determine the following attributes.

Dimensions of x.

Shape of x.

Size of x

In [2]:
import numpy as np
n=[5, 10, 15, 20, 25]
x=np.array(n)
type(x)
print(x.ndim)
print(x.shape)
print(x.size)

1
(5,)
5


### Try 2

Import numpy package as np.

Define the list of lists n = [[-1, -2, -3, -4], [-2,-4, -6, -8]].

Create a numpy array y, using array method of numpy package.

Hint : Pass list n as argument to array method.
Determine the type of array y.

Determine the following attributes.

Dimensions of y.

Shape of y.

Size of y.

Type of each data element of y.

Number of bytes occupied by each data element of y.

In [4]:
import numpy as np
n=[[-1, -2, -3, -4], [-2,-4, -6, -8]] #NOT 2D its just nested list
y=np.array(n)
print(y.ndim)
print(y.shape)
print(y.size)
print(y.dtype)
print(y.nbytes)

2
(2, 4)
8
int64
64


### Try 3

In [6]:
import numpy as np

print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [7]:
np.array(([1, 2], (3,4)))

array([[1, 2],
       [3, 4]])

In [10]:
import numpy as np

z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


### Try 4

Import numpy package as np

Define a ndarray x1 from list, `[[[-1,1],[-2,2]],[[-3 3], [-4, 4]]]

Determine the following attributes of x1

Number of dimensions

Shape

Size

In [13]:
import numpy as np
x=[[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]]
x1=np.array(x)
print(x1.ndim)
print(x1.shape)
print(x1.size)
print(x1)

3
(2, 2, 2)
8
[[[-1  1]
  [-2  2]]

 [[-3  3]
  [-4  4]]]


### Try 5

Import numpy package as np  
Define a ndarray x2, whose shape is (3, 2, 2)  
and contains all 1's.

Define a ndarray x3, whose shape is (4,4) and  
contains 1's on diagonal and 0's elsewhere.

In [19]:
import numpy as np
x2=np.ones(shape=(3,2,2))
print('x2',x2)
x3=np.eye(4)
print('x3',x3)

x2 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
x3 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Try 6

Define a random 3-D array x4 of shape (3, 4, 2)  
and of numbers between 0 and 1.

Simulate a random normal distribution of 20 elements,  
whose mean is 5 and standard deviation 2.5 . Capture the result in x5.

In [20]:
x4=np.linspace(0,1,num=24)
x4

array([0.        , 0.04347826, 0.08695652, 0.13043478, 0.17391304,
       0.2173913 , 0.26086957, 0.30434783, 0.34782609, 0.39130435,
       0.43478261, 0.47826087, 0.52173913, 0.56521739, 0.60869565,
       0.65217391, 0.69565217, 0.73913043, 0.7826087 , 0.82608696,
       0.86956522, 0.91304348, 0.95652174, 1.        ])

In [23]:
x4.shape=(3,4,2)
x4

array([[[0.        , 0.04347826],
        [0.08695652, 0.13043478],
        [0.17391304, 0.2173913 ],
        [0.26086957, 0.30434783]],

       [[0.34782609, 0.39130435],
        [0.43478261, 0.47826087],
        [0.52173913, 0.56521739],
        [0.60869565, 0.65217391]],

       [[0.69565217, 0.73913043],
        [0.7826087 , 0.82608696],
        [0.86956522, 0.91304348],
        [0.95652174, 1.        ]]])

In [24]:
np.random.seed(100)
s=5+2.5*np.random.randn(20)
s

array([0.62558632, 5.85670101, 7.88258951, 4.36890991, 7.45330197,
       6.2855471 , 5.55294917, 2.32489167, 4.52626042, 5.63750361,
       3.85493254, 6.08790872, 3.54101237, 7.04211768, 6.68180201,
       4.73897214, 3.67179906, 7.57433171, 3.90466094, 2.20420438])

### Try 7

Define a ndarray x6, having first 20 even number  
Define a ndarray x7, having equally spaced 30 numbers between 10 and 20.

In [25]:
x6=np.arange(0,41,step=2)
x6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [26]:
x7=np.linspace(10,20,num=30)
x7

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [1]:
Create a ndarray x having first 20 natural numbers, using arange method.

Determine the shape of x.

Change the shape of x to (2, 10) and assign it to new array y.

Split the array y horizontally in to two arrays.

SyntaxError: invalid syntax (<ipython-input-1-23c53b972ba0>, line 1)

In [2]:
Now, Change the shape of x to (4, 5) and assign it to new array z.

Split the array z vertically in to two arrays.

Hint: Use vsplit

SyntaxError: invalid syntax (<ipython-input-2-d5ab1c1ea61d>, line 1)

In [3]:
Create a 2-D array p, of shape (2, 2) with elements 3, 6, 9, 12.

Create a 2-D array q, of shape (2, 3) with elements 15, 18, 21, 24, 27, 30.

Join the two arrays p and q horizontally

SyntaxError: invalid syntax (<ipython-input-3-3f11ad16a48b>, line 1)

In [4]:
Create a array x of shape (6, 5), having first 30 natural numbers.

Obtain elements of last row.

Obtain elements of middle column.

Obtain elements, overlapping first two rows and last three columns.

SyntaxError: invalid syntax (<ipython-input-4-f4227dbb7b62>, line 1)

In [5]:
import numpy as np

x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [8]:
import numpy as np

z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [9]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-2])

[4 5 6 7]


In [10]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]


In [12]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [13]:
import numpy as np

x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [14]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [15]:
import numpy as np

x = np.arange(20).reshape(4, 5)

In [16]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [17]:
import numpy as np

x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [18]:
import numpy as np

x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [19]:
import numpy as np

x = np.arange(4).reshape(2,2)

y = np.vsplit(x,2)
print(y[0])

[[0 1]]


In [20]:
import numpy as np

x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [21]:
import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [22]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [23]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [24]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [25]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [26]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]
